### ISSUE TITLE
Error when installing from .zip file

### ISSUE THREAD

**Issue by xyan326** [amzn/pecos#17]
## Description
Downloaded from the GitHub folder as a zip file and tried to install on local VE. Does not work and produced the error:
...
AssertionError: This does not appear to be a Git repository.
.....
Command errored out with exit status 1: python.....

## How to Reproduce?
Pip install pecos-mainline.zip

**Comment by weiliw-amz** [comment]
Hi xyan326, thanks for your interest in PECOS.

Currently(as of release v0.1.0) PECOS's installation needs to be inside a Git repository for obtaining the version information from Git tags. 
The git repository folder `.git`, are alongside the distribution from `git clone`, but *not* in the `zip` files, and that's the reason for your error.

Could you please try *one* of the following, and they both work:
1. Follow `README`: Clone from GitHub and install
```
git clone https://github.com/amzn/pecos
cd pecos
pip3 install --editable ./
```
2. Download and unzip the file, create a new git repo within it: (This will show an artificial dummy version 0.0.0 because lacking Git repo info, which is not the true version of the package)
```
# unzip
unzip pecos.zip

cd pecos

# initialize repository
git init

pip3 install --editable ./
```

If your VE has problem using Git, or you would rather not use git, please let us know and we will change the underlying requirement for installation.

Thanks!
